# Generated by Django 5.2.6 on 2025-11-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_adminchatroom_chatadminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatadminmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
