# Generated by Django 5.2.6 on 2025-11-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatadminmessage_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatadminmessage',
            name='delivered',
            field=models.BooleanField(default=True),
        ),
    ]
