# Generated by Django 5.2.6 on 2025-10-23 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies', models.PositiveIntegerField()),
                ('company', models.CharField()),
                ('job_title', models.CharField()),
                ('rank', models.CharField(max_length=60)),
                ('avg_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('work_span_from', models.DateTimeField()),
                ('work_span_till', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
