# Generated by Django 5.2.6 on 2025-10-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_admin_workprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprofile',
            name='avg_income',
        ),
        migrations.AddField(
            model_name='workprofile',
            name='avg_daily_income',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=1000),
            preserve_default=False,
        ),
    ]
