# Generated by Django 5.2.6 on 2025-10-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_workprofile_avg_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprofile',
            name='avg_daily_income',
           field=models.DecimalField(decimal_places=2, default=2.0, max_digits=1000),
        ),
    ]
