# Generated by Django 5.2.6 on 2025-10-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_workprofile_avg_daily_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprofile',
            name='total_experience_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workprofile',
            name='avg_daily_income',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workprofile',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workprofile',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
    ]
