# Generated by Django 5.2.6 on 2025-10-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workprofile_total_experience_months_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workprofile',
            old_name='avg_daily_income',
            new_name='avg_daily_incomes',
        ),
    ]
