# Generated by Django 5.2.6 on 2025-10-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_avg_daily_income_workprofile_avg_daily_incomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprofile',
            name='companies',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
