# Generated by Django 5.2.6 on 2025-10-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_workprofile_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprofile',
            name='companies',
        ),
    ]
