# Generated by Django 5.2.6 on 2025-10-26 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_workprofile_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprofile',
            name='rank',
            field=models.CharField(default='No Ranking', max_length=60),
        ),
        migrations.AlterField(
            model_name='workprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
