# Generated by Django 5.2.6 on 2025-10-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_workprofile_rank_alter_workprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workprofile',
            old_name='avg_daily_incomes',
            new_name='avg_hourly_incomes',
        ),
    ]
