# Generated by Django 5.2.6 on 2025-10-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_avg_daily_incomes_workprofile_avg_hourly_incomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprofile',
            name='work_span_till',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
