# Generated by Django 5.2.6 on 2025-10-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_workprofile_work_span_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprofile',
            name='work_span_till',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
