# Generated by Django 5.2.6 on 2025-11-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_workprofile_work_span_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprofile',
            name='job_category',
            field=models.CharField(choices=[('En', 'Engenering'), ('IT', 'Tech'), ('DR', 'Physics'), ('TE', 'Teacher')], default='NO category', max_length=255),
        ),
        migrations.AlterField(
            model_name='workprofile',
            name='company',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='workprofile',
            name='work_span_till',
            field=models.DateTimeField(),
        ),
    ]
