# Generated by Django 5.2.6 on 2025-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_workprofile_job_category_alter_workprofile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprofile',
            name='job_category',
            field=models.CharField(choices=[('En', 'Engenering'), ('IT', 'Tech'), ('DR', 'Physics'), ('TE', 'Teacher'), ('NE', 'NO Category')], default='NO category', max_length=255),
        ),
    ]
