# Generated by Django 5.2.6 on 2025-12-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_workprofile_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('code', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expire', models.DateTimeField()),
            ],
        ),
    ]
