# Generated by Django 5.2.6 on 2025-11-22 20:06

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('field', models.CharField(choices=[('IT', 'Technology'), ('MC', 'Mechanic')])),
                ('members', models.IntegerField()),
                ('locations', models.URLField()),
                ('coordinantes', models.JSONField()),
                ('rating', models.IntegerField()),
                ('avg_income', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_age', models.PositiveIntegerField(default=18, validators=[utils.legal_age_validator])),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ('-rating',),
            },
        ),
    ]
