# Generated by Django 5.2.6 on 2025-11-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_registerd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='field',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=2),
        ),
    ]
