# Generated by Django 5.2.6 on 2025-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_field_alter_company_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCheck',            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('field', models.CharField()),
                ('owner_eid', models.BigIntegerField()),
                ('location', models.URLField()),
                ('certificate', models.FileField(upload_to='')),
                ('created', models.DateTimeField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='locations',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
