# Generated by Django 5.2.6 on 2025-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companycheck_alter_company_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='locations',
            field=models.URLField(),
        ),
    ]
