# Generated by Django 5.2.6 on 2025-11-25 10:52

import django.core.validators
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension




class Migration(migrations.Migration):  

    dependencies = [
        ('companies', '0005_alter_company_locations'),
    ]

    operations = [
        TrigramExtension(
            
            ),
        migrations.AlterModelOptions(
            name='companycheck',
            options={'ordering': ('checked', 'created'), 'verbose_name_plural': 'companiesCheck'},
        ),
        migrations.AddField(
            model_name='companycheck',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companycheck',
            name='status',
            field=models.CharField(choices=[('T', 'Accepted'), ('F', 'Denied'), ('NE', 'checking')], default='checking'),
        ),
        migrations.AlterField(
            model_name='companycheck',
            name='certificate',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='companycheck',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        
    ]
