# Generated by Django 5.2.6 on 2025-11-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycheck',
            name='name_uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
