# Generated by Django 5.2.6 on 2025-11-26 09:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_owner_companycheck_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companycheck',
            name='certificate',
            field=models.FileField(upload_to='certificate/<django.db.models.fields.CharField>', validators=[django.core.validators.FileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='companycheck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_check_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companycheck',
            name='status',
            field=models.CharField(choices=[('T', 'Accepted'), ('F', 'Denied'), ('NE', 'checking')], default='NE'),
        ),
    ]
