# Generated by Django 5.2.6 on 2025-11-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_company_owner_alter_companycheck_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='avg_income',
            new_name='avg_salary',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='legal_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='field',
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companycheck',
            name='name_uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
