# Generated by Django 5.2.6 on 2025-11-29 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_company_company_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_check',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='check_company', to='companies.companycheck'),
        ),
    ]
