# Generated by Django 5.2.6 on 2025-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_alter_company_company_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
